name: boilerplate_mongo
description: Boilerplate for using MongoDB with Jaguar.dart
version: 0.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  jaguar: '>=0.4.3 <0.5.0'
  jaguar_mongo: '>=0.4.0 <0.5.0'
  jaguar_serializer: '>=0.2.1 <0.3.0'
  jaguar_serializer_mongo: '>=0.0.2 <0.1.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
